export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';


export const FETCH_STOREHOUSE = 'FETCH_STOREHOUSE';
export const ADD_STOREHOUSE = 'ADD_STOREHOUSE';
export const UPDATE_STOREHOUSE = 'UPDATE_STOREHOUSE';
export const DELETE_STOREHOUSE = 'DELETE_STOREHOUSE';
export const EDIT_STOREHOUSE = 'EDIT_STOREHOUSE';

export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';

export const FETCH_PRODUCTSEXPORTHISTORY = 'FETCH_PRODUCTSEXPORTHISTORY'