
server:
  port: 3960

spring:
  jackson.serialization.fail-on-empty-beans: false

  http.encoding.charset: UTF-8
  resources.chain.cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
        jdbc:
          batch_size: 50

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vveres?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: sa
    password: 123456789
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

  thymeleaf:
    mode: LEGACYHTML52
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

logging:
  level:
    org:
      hibernate: WARN
      springframework.web: WARN
      apache: WARN
